{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comethru-backend
  labels:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
    component: backend
spec:
  selector:
    matchLabels:
      {{- include "comethru.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "comethru.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.imageTag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CONFIG_IMPORT
              value: "configtree:/etc/secrets/"
            - name: POSTGRES_HOST
              value: "comethru-postgresql"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.primary.service.ports.postgresql }}"
            - name: POSTGRES_ADMIN_USERNAME
              value: "postgres"
            - name: POSTGRES_USER_USERNAME
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
          volumeMounts:
            - name: secrets-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets-volume
          projected:
            sources:
              - secret:
                  name: comethru-backend-secret
              - secret:
                  name: comethru-postgres-secret
              - secret:
                  name: comethru-minio-secret
                  items:
                    - key: rootUser
                      path: MINIO_ROOT_USERNAME
                    - key: rootPassword
                      path: MINIO_ROOT_PASSWORD
{{- end }}