{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comethru.name" . }}-backend
  labels:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
    component: backend
spec:
  selector:
    matchLabels:
      {{- include "comethru.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "comethru.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.imageTag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: "{{ include "comethru.name" . }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "comethru-postgres-password"
            - name: DB_NAME
              value: "comethru"
{{- end }}