apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comethru.name" . }}-frontend
  labels:
    {{- include "comethru.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "comethru.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "comethru.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.imageTag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          env:
            - name: BACKEND_HOST
              value: "{{ include "comethru.name" . }}-backend"
            - name: BACKEND_PORT
              value: "{{ .Values.backend.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP