apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comethru-chart.fullname" . }}-frontend
  labels:
    {{- include "comethru-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "comethru-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "comethru-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.imageTag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          env:
            - name: BACKEND_HOST
              value: "comethru-backend"
            - name: BACKEND_PORT
              value: "80"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP