apiVersion: v1
kind: Service
metadata:
  name: {{ include "comethru-chart.fullname" . }}
  namespace: comethru
  labels:
    {{- include "comethru-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "comethru-chart.selectorLabels" . | nindent 4 }}