# Default values for comethru-chart.

appName: "comethru"

nginx:
  enabled: true
  image: nginx:alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  upstreamService: "comethru"  # The service name of your frontend app
  upstreamPort: 80  # The port on which your frontend service is exposed

backend:
  enabled: true
  image: "alexpetrusca/comethru-backend"
  imageTag: "latest"
  pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

postgresql:
  enabled: true
  auth:
    database: "comethru"
    username: "comethru"
    existingSecret: "comethru-postgres-secret"
    secretKeys:
      adminPasswordKey: "POSTGRES_ADMIN_PASSWORD"
      userPasswordKey: "POSTGRES_USER_PASSWORD"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""
    service:
      ports:
        postgresql: 5432

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Allow local connections
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

ingress-nginx:
  enabled: true
  controller:
    namespaceOverride: "comethru"  # Deploy ingress controller to comethru namespace
    service:
      type: LoadBalancer
      ports:
        http: 80  # Change to whatever port you want
        https: 443  # Also change HTTPS if needed
    hostNetwork: false # Enable hostNetwork to bind directly to the host's network # todo check this out
    admissionWebhooks:
      enabled: false
    config:
      use-proxy-protocol: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"

minio:
  enabled: true
  mode: standalone
  existingSecret: "comethru-minio-secret"
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""  # Use default storage class
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  service:
    type: ClusterIP
    port: 9000
  consoleService:
    type: ClusterIP
    port: 9001
  buckets:
    - name: images
      policy: none
      purge: false
  policies:
    - name: user-policy
      statements:
        - resources:
            - 'arn:aws:s3:::images/*'
          actions:
            - "s3:GetObject"
            - "s3:PutObject"
kafka:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  zookeeper:
    enabled: false
  kraft:
    enabled: true
