# Default values for comethru-chart.

nameOverride: ""
fullnameOverride: "comethru"

nginx:
  enabled: true
  image: nginx:alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  upstreamService: "comethru"  # The service name of your frontend app
  upstreamPort: 80  # The port on which your frontend service is exposed

frontend:
  image: "alexpetrusca/comethru-frontend"
  imageTag: "latest"
  pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP  # Using ClusterIP since we'll access via ingress
    port: 80
    targetPort: 3000

backend:
  enabled: true
  image: "alexpetrusca/comethru-backend"
  imageTag: "latest"
  pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: "comethru-postgres-password" # todo: remove later - no password in code
    database: "comethru"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""
    service:
      ports:
        postgresql: 5432

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Allow local connections
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

ingress-nginx:
  enabled: true
  controller:
    namespaceOverride: "comethru"  # Deploy ingress controller to comethru namespace
    service:
      type: LoadBalancer
      ports:
        http: 80  # Change to whatever port you want
        https: 443  # Also change HTTPS if needed
    hostNetwork: false # Enable hostNetwork to bind directly to the host's network # todo check this out
    admissionWebhooks:
      enabled: false
    config:
      use-proxy-protocol: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"