spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: comethru-postgres-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'none' if you're using Option 3 (manual/init scripts)
      # 'update' if you want Hibernate to auto-create tables for now
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  service-sid: ${TWILIO_SERVICE_SID}

rsa:
  public-key: ${RSA_PUBLIC_KEY}
  private-key: ${RSA_PRIVATE_KEY}