spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
    username: ${POSTGRES_ADMIN_USERNAME}
    password: ${POSTGRES_ADMIN_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # auto-update tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

integration:
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    service-sid: ${TWILIO_SERVICE_SID}

security:
  auth:
    session:
      duration: 24h
    cookie:
      name: AUTH_TOKEN
      secure: false
      same-site: Lax
    rsa:
      public-key: ${RSA_PUBLIC_KEY}
      private-key: ${RSA_PRIVATE_KEY}

logging:
  level:
    root: DEBUG